/* Sound effects, visible-hand evaluator, and player HUD. Core server game logic is unchanged. */
let soundOn=localStorage.getItem('holdem_sound')!=='0';
let audioCtx=null;
let soundTrack={ready:false,handId:null,board:0,action:'',turn:null,completed:null};
function ensureAudio(){if(!soundOn)return null;try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
document.addEventListener('pointerdown',()=>ensureAudio(),{capture:true});
function tone(freq,duration=.08,type='sine',volume=.035,delay=0){const c=ensureAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,volume),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+duration+.02)}
function chipNoise(duration=.045,volume=.025,delay=0){const c=ensureAudio();if(!c)return;const len=Math.max(1,Math.floor(c.sampleRate*duration)),buf=c.createBuffer(1,len,c.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain(),t=c.currentTime+delay;src.buffer=buf;filter.type='bandpass';filter.frequency.value=2300;filter.Q.value=.7;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(filter);filter.connect(g);g.connect(c.destination);src.start(t)}
function playFx(kind){if(!soundOn)return;switch(kind){case'deal':chipNoise(.055,.032);tone(330,.055,'triangle',.018,.015);break;case'check':tone(420,.045,'square',.018);break;case'call':chipNoise(.04,.028);tone(520,.07,'triangle',.022,.02);break;case'raise':chipNoise(.05,.035);tone(520,.07,'triangle',.025,.01);tone(720,.09,'triangle',.026,.075);break;case'allin':tone(240,.11,'sawtooth',.022);tone(360,.12,'triangle',.03,.09);tone(520,.14,'triangle',.032,.18);break;case'turn':tone(880,.08,'sine',.03);tone(1175,.11,'sine',.025,.09);break;case'win':tone(523,.12,'triangle',.035);tone(659,.12,'triangle',.035,.11);tone(784,.16,'triangle',.038,.22);tone(1047,.23,'sine',.03,.34);break;case'fold':tone(190,.08,'triangle',.018);break;default:tone(440,.05,'sine',.015)}}
function actionFx(type){return({CHECK:'check',AUTO_CHECK:'check',CALL:'call',BET:'raise',RAISE:'raise',ALL_IN:'allin',FOLD:'fold',AUTO_FOLD:'fold'}[type]||'')}
function syncGameSounds(member){if(!state?.hand)return;const h=state.hand,recent=state.recentActions?.at(-1);const actionKey=recent?`${h.id}:${recent.seq??''}:${recent.playerId??''}:${recent.type}:${recent.amount??''}:${recent.raiseTo??''}`:'';const turn=h.currentActorPlayerId;const boardCount=state.board?.length||0;const completed=h.street==='HAND_COMPLETE'?h.id:null;if(!soundTrack.ready){soundTrack={ready:true,handId:h.id,board:boardCount,action:actionKey,turn,completed};return}if(soundTrack.handId!==h.id){playFx('deal');soundTrack.handId=h.id;soundTrack.board=0;soundTrack.completed=null}synchronizeAction:if(actionKey&&actionKey!==soundTrack.action){const fx=actionFx(recent.type);if(fx)playFx(fx)}if(boardCount>soundTrack.board)playFx('deal');if(turn===state.me?.playerId&&soundTrack.turn!==state.me?.playerId&&h.street!=='HAND_COMPLETE')playFx('turn');if(completed&&completed!==soundTrack.completed){const mine=(state.results||[]).some(r=>r.playerId===state.me?.playerId&&Number(r.payout)>0);playFx(mine?'win':'check')}soundTrack.action=actionKey;soundTrack.board=boardCount;soundTrack.turn=turn;soundTrack.completed=completed}
const RV={2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13,A:14};
function parseCard(c){return{r:RV[c.slice(0,-1)]||0,s:c.slice(-1)}}
function rname(v){return({14:'A',13:'K',12:'Q',11:'J'}[v]||String(v))}
function cmpScore(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function fiveScore(cards){const a=cards.map(parseCard),ranks=a.map(x=>x.r).sort((x,y)=>y-x),counts={};ranks.forEach(r=>counts[r]=(counts[r]||0)+1);const groups=Object.entries(counts).map(([r,n])=>({r:+r,n})).sort((x,y)=>y.n-x.n||y.r-x.r);const flush=a.every(x=>x.s===a[0].s);let uniq=[...new Set(ranks)];if(uniq[0]===14)uniq.push(1);let straightHigh=0;for(let i=0;i<=uniq.length-5;i++)if(uniq[i]-uniq[i+4]===4){straightHigh=uniq[i];break}if(flush&&straightHigh)return{v:[8,straightHigh],label:straightHigh===14?'로열 플러시':`${rname(straightHigh)} 하이 스트레이트 플러시`};if(groups[0].n===4)return{v:[7,groups[0].r,groups[1].r],label:`${rname(groups[0].r)} 포카드`};if(groups[0].n===3&&groups[1]?.n===2)return{v:[6,groups[0].r,groups[1].r],label:`${rname(groups[0].r)} 풀하우스`};if(flush)return{v:[5,...ranks],label:`${rname(ranks[0])} 하이 플러시`};if(straightHigh)return{v:[4,straightHigh],label:`${rname(straightHigh)} 하이 스트레이트`};if(groups[0].n===3){const k=groups.filter(g=>g.n===1).map(g=>g.r).sort((x,y)=>y-x);return{v:[3,groups[0].r,...k],label:`${rname(groups[0].r)} 트리플`}}const pairs=groups.filter(g=>g.n===2).sort((x,y)=>y.r-x.r);if(pairs.length>=2){const k=groups.filter(g=>g.n===1).map(g=>g.r).sort((x,y)=>y-x)[0]||0;return{v:[2,pairs[0].r,pairs[1].r,k],label:`${rname(pairs[0].r)}/${rname(pairs[1].r)} 투페어`}}if(pairs.length===1){const k=groups.filter(g=>g.n===1).map(g=>g.r).sort((x,y)=>y-x);return{v:[1,pairs[0].r,...k],label:`${rname(pairs[0].r)} 원페어`}}return{v:[0,...ranks],label:`${rname(ranks[0])} 하이`}}
function combos5(arr){const out=[];for(let a=0;a<arr.length-4;a++)for(let b=a+1;b<arr.length-3;b++)for(let c=b+1;c<arr.length-2;c++)for(let d=c+1;d<arr.length-1;d++)for(let e=d+1;e<arr.length;e++)out.push([arr[a],arr[b],arr[c],arr[d],arr[e]]);return out}
function visibleHandLabel(){const cards=[...(state?.private?.holeCards||[]),...(state?.board||[])].filter(Boolean);if(cards.length===0)return '카드 없음';if(cards.length<5){const ps=cards.map(parseCard),cnt={};ps.forEach(x=>cnt[x.r]=(cnt[x.r]||0)+1);const pair=Object.entries(cnt).filter(([,n])=>n>=2).map(([r])=>+r).sort((a,b)=>b-a)[0];if(pair)return `${rname(pair)} 원페어`;return `${rname(Math.max(...ps.map(x=>x.r)))} 하이`}let best=null;for(const c of combos5(cards)){const s=fiveScore(c);if(!best||cmpScore(s.v,best.v)>0)best=s}return best?.label||state?.private?.currentMadeHand||'계산 중'}
function profitKey(){return `holdem_profit_${state?.room?.code||''}_${state?.me?.playerId||''}`}
function settledProfit(member){const start=Number(state?.room?.settings?.startingStack||0);if(state?.hand?.street==='HAND_COMPLETE'){const p=Number(member?.stack||0)-start;localStorage.setItem(profitKey(),String(p));return p}const saved=localStorage.getItem(profitKey());return saved==null?0:Number(saved)||0}
const originalRenderTable=renderTable;
renderTable=function(member){syncGameSounds(member);const max=state.room.maxPlayers,mySeat=member.seatNo||1;const seats=Array.from({length:max},(_,i)=>i+1).map(s=>{const rel=(s-mySeat+max)%max,pos=seatPosition(rel,max),p=state.players.find(x=>x.seatNo===s);return renderSeat(p,s,pos)}).join('');const recent=state.recentActions?.at(-1),recName=recent?state.players.find(p=>p.playerId===recent.playerId)?.displayName:'',recText=recent?`${recName||''} · ${actionKo(recent.type)}${recent.raiseTo?' '+fmt(recent.raiseTo):recent.amount?' '+fmt(recent.amount):''}`:'';const own=state.private?.holeCards||[],isTurn=state.hand?.currentActorPlayerId===state.me?.playerId,allowed=state.private?.allowedActions,handDone=state.hand?.street==='HAND_COMPLETE',profit=settledProfit(member),made=visibleHandLabel();return `<div class="player-hud"><div class="hud-box chips"><span>내 칩</span><b>${fmt(member.stack)}</b></div><div class="hud-box profit ${profit>0?'positive':profit<0?'negative':''}"><span>수익</span><b>${profit>0?'+':''}${fmt(profit)}</b></div><div class="hud-box hand"><span>현재 패</span><b>${esc(made)}</b></div></div><section class="stage"><div class="poker-table">${state.room.status==='PAUSED'?'<div class="paused"><b>게임 일시정지</b></div>':''}<div class="table-center"><span class="street-pill">${streetKo(state.hand?.street)}</span><div class="community">${state.board.map(c=>card(c,true)).join('')}${Array.from({length:Math.max(0,5-state.board.length)},()=>'<div class="slot"></div>').join('')}</div><div class="pot">Pot ${fmt(state.hand?.potTotal)}</div>${state.pots?.filter(p=>p.type==='SIDE').map(p=>`<div class="tiny muted">Side ${p.index} · ${fmt(p.amount)}</div>`).join('')||''}${recText?`<div class="recent">${esc(recText)}</div>`:''}</div>${seats}</div><div class="my-panel"><div class="my-cards">${own.map(c=>card(c)).join('')}</div><div class="made">현재 패 · ${esc(made)}</div></div>${handDone?renderResults():''}</section>${!handDone&&isTurn&&state.room.status!=='PAUSED'?renderActions(allowed):`<div class="waitbar">${state.room.status==='PAUSED'?'방장이 게임을 재개할 때까지 대기 중':handDone?'다음 Hand를 준비 중…':'상대방의 액션을 기다리는 중…'}</div>`}`}
const originalOpenMenu=openMenu;
openMenu=function(){const m=state.players.find(p=>p.playerId===state.me.playerId);modal.innerHTML=`<div class="backdrop" id="backdrop"><section class="sheet"><div class="sheet-head"><h3>게임 설정</h3><button class="x" data-close>×</button></div><button class="menu-row" id="soundToggle"><span class="sound-state ${soundOn?'':'off'}">효과음</span><small>${soundOn?'켜짐':'꺼짐'}</small></button><button class="menu-row" id="sitout"><span>${m?.status==='SIT_OUT'?'게임 복귀':'자리 비움'}</span><small>${m?.status==='SIT_OUT'?'다음 Hand부터 참가':'현재 Hand 후 적용'}</small></button>${state.room.isHost?`<button class="menu-row" id="pause"><span>${state.room.status==='PAUSED'?'게임 재개':'게임 일시정지'}</span><small>방장 기능</small></button>`:''}<button class="menu-row" id="leave"><span style="color:#ff9da2">게임 나가기</span><small>현재 Hand 칩은 유지</small></button></section></div>`;modal.querySelector('[data-close]').onclick=closeModal;document.getElementById('backdrop').onclick=e=>{if(e.target.id==='backdrop')closeModal()};document.getElementById('soundToggle').onclick=e=>{soundOn=!soundOn;localStorage.setItem('holdem_sound',soundOn?'1':'0');if(soundOn){ensureAudio();playFx('turn')}const s=e.currentTarget.querySelector('.sound-state'),small=e.currentTarget.querySelector('small');s.classList.toggle('off',!soundOn);small.textContent=soundOn?'켜짐':'꺼짐'};document.getElementById('sitout').onclick=()=>{closeModal();command({op:'sitOut',code:state.room.code,sitOut:m?.status!=='SIT_OUT'})};const p=document.getElementById('pause');if(p)p.onclick=()=>{closeModal();command({op:'pause',code:state.room.code,paused:state.room.status!=='PAUSED'})};document.getElementById('leave').onclick=async()=>{if(!confirm('게임에서 나갈까요?'))return;try{await api({op:'leave',code:state.room.code});setToken('');history.pushState({},'',location.pathname);closeModal();renderHome()}catch(e){showToast(e.message)}}}
if(state)renderRoom();
