const API='https://vxrsgcsxquaunvxnlkcv.supabase.co/functions/v1/holdem-api';
const K='holdem_session_v2';
const app=document.getElementById('app'), modal=document.getElementById('modal'), toastEl=document.getElementById('toast'), net=document.getElementById('net');
let token=localStorage.getItem(K)||'', state=null, poll=null, busy=false, disconnected=false, seconds=null, timerTick=null, autoNextId=null, raiseValue=0, creating=false, homeName=localStorage.getItem('holdem_name')||'';
const fmt=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function getCode(){const m=location.pathname.match(/^\/room\/([A-Z0-9]{6})/i);return m?m[1].toUpperCase():new URLSearchParams(location.search).get('room')?.toUpperCase()||''}
function goRoom(code){history.pushState({},'',`?room=${code}`); stopPoll(); loadRoom(false)}
window.addEventListener('popstate',()=>{stopPoll(); state=null; renderRoute()});
function showToast(msg){toastEl.textContent=msg;toastEl.classList.remove('hidden');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.add('hidden'),3000)}
function setNet(on){disconnected=on;net.classList.toggle('hidden',!on)}
async function api(body,withToken=true){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json',...(withToken&&token?{'x-holdem-session':token}:{})},body:JSON.stringify(body)});const j=await r.json().catch(()=>({ok:false,message:'서버 응답 오류'}));if(!r.ok||!j.ok)throw Object.assign(new Error(j.message||'요청 실패'),{code:j.code,data:j});return j}
function setToken(t){token=t||'';if(token)localStorage.setItem(K,token);else localStorage.removeItem(K)}
function cardObj(c){if(!c)return null;const suit=c.slice(-1),rank=c.slice(0,-1),sym={S:'♠',H:'♥',D:'♦',C:'♣'}[suit]||suit;return{rank,sym,red:suit==='H'||suit==='D'}}
function card(c,small=false){const x=cardObj(c);return `<div class="card-ui ${small?'small ':''}${x?.red?'red':''}"><b>${esc(x?.rank||'')}</b><em>${esc(x?.sym||'')}</em></div>`}
function back(small=true){return `<div class="card-ui back ${small?'small':''}"></div>`}
function routeCode(){return getCode()}
function renderRoute(){const code=routeCode(); if(code){loadRoom(false)}else renderHome()}
function renderHome(){state=null;stopPoll();app.innerHTML=`<main class="center"><section class="home"><div class="brand"><div class="brand-mark">H</div><div><h1>Hold'em</h1><p>친구들과 즐기는 무료 플레이머니 홀덤</p></div></div><div class="card stack"><div class="field"><label>닉네임</label><input id="homeName" class="input" maxlength="20" placeholder="닉네임" value="${esc(homeName)}" /></div><button id="createBtn" class="btn primary">방 만들기</button><div class="divider">또는</div><div class="field"><label>방 코드</label><input id="joinCode" class="input" maxlength="6" placeholder="예: A7KD92" autocapitalize="characters" /></div><button id="joinBtn" class="btn secondary">방 참가하기</button></div></section></main>`;document.getElementById('createBtn').onclick=()=>openCreate();document.getElementById('joinBtn').onclick=async()=>{const n=document.getElementById('homeName').value.trim(),c=document.getElementById('joinCode').value.trim().toUpperCase();if(!n)return showToast('닉네임을 입력해주세요.');if(c.length!==6)return showToast('6자리 방 코드를 입력해주세요.');const btn=document.getElementById('joinBtn');if(btn.disabled)return;btn.disabled=true;btn.textContent='입장 중…';homeName=n;localStorage.setItem('holdem_name',n);try{const j=await api({op:'joinRoom',code:c,displayName:n},true);setToken(j.token);goRoom(c)}catch(e){showToast(e.message);btn.disabled=false;btn.textContent='방 참가하기'}}}
function openCreate(){const n=document.getElementById('homeName')?.value.trim();if(!n)return showToast('닉네임을 입력해주세요.');homeName=n;localStorage.setItem('holdem_name',n);modal.innerHTML=`<div class="backdrop" id="backdrop"><section class="sheet"><div class="sheet-head"><h3>방 만들기</h3><button class="x" data-close>×</button></div><div class="stack"><div class="field"><label>방 이름</label><input id="roomName" class="input" maxlength="40" value="친구 홀덤" /></div><div class="field"><label>최대 인원</label><div class="seg" id="maxSeg">${[2,3,4,5,6].map(x=>`<button data-v="${x}" class="${x===6?'on':''}">${x}</button>`).join('')}</div></div><div class="field"><label>시작 칩</label><input id="stack" class="input" type="number" value="10000" min="100" /></div><div class="two"><div class="field"><label>SB</label><input id="sb" class="input" type="number" value="50" min="1" /></div><div class="field"><label>BB</label><input id="bb" class="input" type="number" value="100" min="2" /></div></div><div class="field"><label>액션 시간</label><div class="seg" id="timerSeg">${[[15,'15초'],[30,'30초'],[45,'45초'],['null','없음']].map(([v,l])=>`<button data-v="${v}" class="${v===30?'on':''}">${l}</button>`).join('')}</div></div><div class="toggle"><span>관전자 허용</span><button id="spectator" class="switch"><i></i></button></div><button id="makeRoom" class="btn primary">방 만들기</button></div></section></div>`;let max=6,timer=30,spec=false;modal.querySelectorAll('#maxSeg button').forEach(b=>b.onclick=()=>{max=+b.dataset.v;modal.querySelectorAll('#maxSeg button').forEach(x=>x.classList.toggle('on',x===b))});modal.querySelectorAll('#timerSeg button').forEach(b=>b.onclick=()=>{timer=b.dataset.v==='null'?null:+b.dataset.v;modal.querySelectorAll('#timerSeg button').forEach(x=>x.classList.toggle('on',x===b))});document.getElementById('spectator').onclick=e=>{spec=!spec;e.currentTarget.classList.toggle('on',spec)};modal.querySelector('[data-close]').onclick=closeModal;document.getElementById('backdrop').onclick=e=>{if(e.target.id==='backdrop')closeModal()};document.getElementById('makeRoom').onclick=async()=>{if(creating)return;const sb=+document.getElementById('sb').value,bb=+document.getElementById('bb').value;if(!(bb>sb&&sb>0))return showToast('BB는 SB보다 커야 합니다.');creating=true;document.getElementById('makeRoom').disabled=true;try{const j=await api({op:'createRoom',displayName:homeName,roomName:document.getElementById('roomName').value.trim()||'친구 홀덤',maxPlayers:max,startingStack:+document.getElementById('stack').value||10000,smallBlind:sb,bigBlind:bb,actionTimerSeconds:timer,spectatorEnabled:spec},false);setToken(j.token);closeModal();goRoom(j.code)}catch(e){showToast(e.message)}finally{creating=false}}}
function closeModal(){modal.innerHTML=''}
async function loadRoom(quiet=true){const code=routeCode();if(!code)return renderHome();if(!token){renderInvite(code);return}try{const j=await api({op:'state',code});const next=j.state;const member=next?.players?.find(p=>p.playerId===next?.me?.playerId);if(!member){state=null;stopPoll();setNet(false);renderInvite(code);return}state=next;setNet(false);renderRoom();startPoll()}catch(e){if(e.code==='SESSION_INVALID'){setToken('');state=null;stopPoll();renderInvite(code)}else if(e.code==='ROOM_NOT_JOINED'||e.code==='ROOM_NOT_FOUND'){state=null;stopPoll();setNet(false);renderInvite(code)}else if(!quiet){app.innerHTML=`<main class="center"><section class="card"><p class="error">${esc(e.message)}</p><button class="btn secondary" id="homeAfterError">홈으로</button></section></main>`;document.getElementById('homeAfterError')?.addEventListener('click',()=>{history.pushState({},'',location.pathname);renderHome()})}else setNet(true)}}
function renderInvite(code){stopPoll();state=null;app.innerHTML=`<main class="center"><section class="home"><div class="brand"><div class="brand-mark">H</div><div><h1>Hold'em</h1><p>초대받은 방 · #${esc(code)}</p></div></div><div class="card stack"><div class="field"><label>닉네임</label><input id="inviteName" class="input" maxlength="20" placeholder="닉네임" value="${esc(homeName)}" autofocus /></div><button id="enterRoom" class="btn primary">입장하기</button><button id="otherRoom" class="btn secondary">다른 방 찾기</button></div></section></main>`;document.getElementById('otherRoom').onclick=()=>{history.pushState({},'',location.pathname);renderHome()};document.getElementById('enterRoom').onclick=async()=>{const n=document.getElementById('inviteName').value.trim();if(!n)return showToast('닉네임을 입력해주세요.');const btn=document.getElementById('enterRoom');if(btn.disabled)return;btn.disabled=true;btn.textContent='입장 중…';try{const j=await api({op:'joinRoom',code,displayName:n},true);homeName=n;localStorage.setItem('holdem_name',n);setToken(j.token);await loadRoom(false)}catch(e){showToast(e.message);btn.disabled=false;btn.textContent='입장하기'}}}
function startPoll(){if(poll)return;poll=setInterval(()=>loadRoom(true),1000)}function stopPoll(){if(poll){clearInterval(poll);poll=null}if(timerTick){clearInterval(timerTick);timerTick=null}}
function seatPosition(rel,max){const sets={2:[0,3],3:[0,2,4],4:[0,2,3,4],5:[0,1,2,4,5],6:[0,1,2,3,4,5]};return sets[max]?.[rel]??rel}
function renderRoom(){if(!state)return;const meId=state.me?.playerId,member=state.players.find(p=>p.playerId===meId),seated=!!member?.seatNo,active=state.hand&&state.hand.street!=='HAND_COMPLETE',showTable=seated&&!!state.hand;app.innerHTML=`<main class="room-shell"><header class="game-header"><div><strong>${esc(state.room.name)}</strong><span class="room-code">#${esc(state.room.code)}</span></div><div class="header-actions"><button class="icon-btn" id="share">초대</button><button class="icon-btn" id="history">기록</button><button class="icon-btn" id="ranks">족보</button><button class="icon-btn" id="menu">설정</button></div></header>${!showTable?renderLobby(member):renderTable(member)}</main>`;wireHeader();if(!showTable)wireLobby(member);else wireTable(member);scheduleAutoNext()}
function renderLobby(member){const seated=!!member?.seatNo,canStart=state.room.isHost&&state.players.filter(p=>p.seatNo&&p.status==='ACTIVE').length>=2;return `<section class="lobby"><div class="lobby-top"><div class="code-box"><small>방 코드</small><b>${esc(state.room.code)}</b></div><button id="copyCode" class="btn secondary" style="height:62px;padding:0 14px">복사</button></div><div class="lobby-settings"><span>시작 칩<b>${fmt(state.room.settings.startingStack)}</b></span><span>블라인드<b>${fmt(state.room.settings.smallBlind)} / ${fmt(state.room.settings.bigBlind)}</b></span><span>타이머<b>${state.room.settings.actionTimerSeconds?state.room.settings.actionTimerSeconds+'초':'없음'}</b></span></div><div class="seat-grid">${Array.from({length:state.room.maxPlayers},(_,i)=>i+1).map(n=>{const p=state.players.find(x=>x.seatNo===n);return `<button class="seat-choice ${p?'occupied':''}" data-seat="${n}" ${p?'disabled':''}><span>Seat ${n}</span><b>${p?esc(p.displayName):(seated?'빈 자리':'앉기')}</b></button>`}).join('')}</div>${!seated?'<p class="host-note">빈 좌석을 선택하세요.</p>':state.room.isHost?`<button id="startHand" class="btn primary" style="width:100%" ${canStart?'':'disabled'}>게임 시작</button><p class="host-note">2명 이상 착석하면 시작할 수 있습니다.</p>`:'<p class="host-note">방장이 게임을 시작할 때까지 기다려주세요.</p>'}</section>`}
function wireLobby(member){document.getElementById('copyCode').onclick=()=>copyText(state.room.code);document.querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>command({op:'seat',code:state.room.code,seatNo:+b.dataset.seat}));const s=document.getElementById('startHand');if(s)s.onclick=()=>command({op:'start',code:state.room.code})}
