/* Luxury audio layer: procedural SFX + low-volume loopable BGM. */
let bgmMode=localStorage.getItem('holdem_bgm')||'jazz';
let bgmTimer=null,bgmBar=0,lastTimerPulse=-1;
function luxAudio(){try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
function envTone(freq,dur=.08,type='sine',vol=.02,delay=0,endFreq=null){const c=luxAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+dur+.03)}
function filteredNoise(dur=.08,vol=.02,freq=1600,q=.7,delay=0,type='bandpass'){const c=luxAudio();if(!c)return;const len=Math.max(1,Math.floor(c.sampleRate*dur)),buf=c.createBuffer(1,len,c.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain(),t=c.currentTime+delay;src.buffer=buf;f.type=type;f.frequency.value=freq;f.Q.value=q;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);src.connect(f);f.connect(g);g.connect(c.destination);src.start(t)}
function chipClack(delay=0,vol=.026){filteredNoise(.024,vol,2600,1.5,delay);envTone(1450,.025,'triangle',vol*.55,delay)}
function glassTap(){envTone(1180,.035,'sine',.012);envTone(1760,.04,'sine',.008,.014)}
playFx=function(kind){if(!soundOn)return;switch(kind){case'deal':filteredNoise(.115,.024,1350,.65,0,'bandpass');envTone(220,.055,'triangle',.008,.035);filteredNoise(.055,.015,2100,.8,.085);break;case'check':glassTap();break;case'call':chipClack(0,.026);chipClack(.045,.018);break;case'raise':chipClack(0,.028);chipClack(.038,.025);chipClack(.078,.021);envTone(460,.06,'triangle',.012,.07);break;case'allin':chipClack(0,.032);chipClack(.035,.030);chipClack(.07,.028);chipClack(.105,.025);envTone(118,.20,'sine',.018,.01,72);envTone(520,.12,'triangle',.018,.14);break;case'fold':filteredNoise(.13,.018,1150,.55,0,'bandpass');envTone(180,.07,'triangle',.007,.055);break;case'turn':envTone(760,.065,'sine',.020);envTone(1010,.08,'sine',.016,.075);break;case'timer':envTone(82,.09,'sine',.022,0,62);break;case'win':for(let i=0;i<7;i++)chipClack(i*.042,.020*(1-i*.06));filteredNoise(.18,.018,920,.5,.02);envTone(523,.13,'triangle',.025,.18);envTone(659,.13,'triangle',.025,.29);envTone(784,.16,'triangle',.026,.40);envTone(1047,.22,'sine',.020,.54);break;default:glassTap()}}
function bgTone(freq,dur,type='sine',vol=.006,delay=0){envTone(freq,dur,type,vol,delay)}
function bgBrush(delay=0,vol=.004){filteredNoise(.13,vol,3800,.35,delay,'highpass')}
function jazzBar(){if(bgmMode!=='jazz')return;const roots=[55,65.41,73.42,49],root=roots[bgmBar%roots.length];[0,.72,1.44,2.16].forEach((d,i)=>{bgTone(i===3?root*.89:root,.44,'triangle',.009,d);if(i===1||i===3)bgBrush(d+.36,.0035)});bgTone(root*2,.50,'sine',.0035,.18);bgTone(root*3,.46,'sine',.003,.18);if(bgmBar%2===1){bgTone(root*4,.18,'sawtooth',.0035,1.02);bgTone(root*4.5,.14,'sawtooth',.003,1.28);bgTone(root*5,.24,'sawtooth',.0032,1.60)}bgmBar++}
function houseKick(delay=0){const c=luxAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type='sine';o.frequency.setValueAtTime(92,t);o.frequency.exponentialRampToValueAtTime(46,t+.13);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.014,t+.005);g.gain.exponentialRampToValueAtTime(.0001,t+.20);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.22)}
function houseBar(){if(bgmMode!=='house')return;const roots=[55,61.74,65.41,49],r=roots[bgmBar%roots.length];[0,.5,1,1.5].forEach((d,i)=>{houseKick(d);bgTone(i%2?r:r*.5,.32,'sine',.008,d+.02)});[r*2,r*2.5,r*3].forEach((f,i)=>bgTone(f,1.78,'triangle',.0024+i*.00025,.10));filteredNoise(.045,.0027,5200,.5,.25,'highpass');filteredNoise(.045,.0027,5200,.5,1.25,'highpass');bgmBar++}
function stopBgm(){if(bgmTimer){clearInterval(bgmTimer);bgmTimer=null}}
function startBgm(mode=bgmMode){bgmMode=mode;localStorage.setItem('holdem_bgm',mode);stopBgm();if(mode==='off')return;luxAudio();bgmBar=0;if(mode==='jazz'){jazzBar();bgmTimer=setInterval(jazzBar,2880)}else{houseBar();bgmTimer=setInterval(houseBar,2000)}}
function bgmLabel(){return bgmMode==='jazz'?'Noir Jazz':bgmMode==='house'?'Deep House':'꺼짐'}
let bgmArmed=false;document.addEventListener('pointerdown',()=>{luxAudio();if(!bgmArmed){bgmArmed=true;if(bgmMode!=='off')startBgm(bgmMode)}},{capture:true});
const luxuryTick=tickTimer;tickTimer=function(){luxuryTick();if(seconds!=null&&seconds>0&&seconds<=5&&seconds!==lastTimerPulse){lastTimerPulse=seconds;playFx('timer')}if(seconds==null||seconds>5)lastTimerPulse=-1};
const luxuryRenderTable=renderTable;renderTable=function(member){return luxuryRenderTable(member).replace('<span>수익</span>','<span>딴 금액</span>')};
const luxuryMenu=openMenu;openMenu=function(){luxuryMenu();const s=document.getElementById('soundToggle');if(!s)return;const row=document.createElement('button');row.className='menu-row';row.id='bgmToggle';row.innerHTML=`<span>배경음악</span><small>${bgmLabel()}</small>`;s.insertAdjacentElement('afterend',row);row.onclick=()=>{const next=bgmMode==='jazz'?'house':bgmMode==='house'?'off':'jazz';startBgm(next);row.querySelector('small').textContent=bgmLabel();glassTap()}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.classList.contains('action')||b.id==='soundToggle'||b.id==='bgmToggle')return;if(soundOn)glassTap()},{capture:true});

/* Korean action voice guide + state-linked visual effects */
let voiceOn=localStorage.getItem('holdem_voice')!=='0';
let visualActionKey='',visualHandId='',visualBoardCount=0,voiceActionKey='';
function speakKo(text){if(!voiceOn||!('speechSynthesis'in window)||!text)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.92;u.pitch=.90;u.volume=.58;const voices=speechSynthesis.getVoices?.()||[];const ko=voices.find(v=>/^ko/i.test(v.lang));if(ko)u.voice=ko;speechSynthesis.speak(u)}catch{}}
function voiceForAction(type){return({CHECK:'체크',AUTO_CHECK:'체크',CALL:'콜',BET:'베팅',RAISE:'레이즈',ALL_IN:'올인',FOLD:'폴드',AUTO_FOLD:'폴드'}[type]||'')}
function recentKey(h,recent){return recent?`${h.id}:${recent.seq??''}:${recent.playerId??''}:${recent.type}:${recent.amount??''}:${recent.raiseTo??''}`:''}
function visualSeatPos(playerId){const max=state?.room?.maxPlayers||6,me=state?.players?.find(p=>p.playerId===state.me?.playerId),p=state?.players?.find(p=>p.playerId===playerId);if(!me?.seatNo||!p?.seatNo)return 0;return seatPosition((p.seatNo-me.seatNo+max)%max,max)}
function animateChip(playerId){setTimeout(()=>{const table=document.querySelector('.poker-table');if(!table)return;const x=document.createElement('i');x.className=`chip-fx from${visualSeatPos(playerId)}`;table.appendChild(x);setTimeout(()=>x.remove(),650)},0)}
function animateDeal(){setTimeout(()=>{const table=document.querySelector('.poker-table');if(!table)return;const seats=[...document.querySelectorAll('.poker-table .seat')].filter(x=>!x.classList.contains('empty'));seats.forEach((seat,i)=>{const cls=[...seat.classList].find(c=>/^pos\d$/.test(c))||'pos0',pos=cls.replace('pos','');const x=document.createElement('i');x.className=`deal-fx to${pos}`;x.style.animationDelay=`${i*.045}s`;table.appendChild(x);setTimeout(()=>x.remove(),750+i*50)})},0)}
function animateWin(){setTimeout(()=>{document.querySelector('.seat.me')?.classList.add('win-glow');setTimeout(()=>document.querySelector('.seat.me')?.classList.remove('win-glow'),1000)},0)}
const premiumSync=syncGameSounds;
syncGameSounds=function(member){const h=state?.hand,recent=state?.recentActions?.at(-1),key=h?recentKey(h,recent):'';const prevHand=visualHandId,prevBoard=visualBoardCount;premiumSync(member);if(!h)return;if(key&&key!==visualActionKey){if(['CALL','BET','RAISE','ALL_IN'].includes(recent.type))animateChip(recent.playerId);visualActionKey=key}if(key&&key!==voiceActionKey){const word=voiceForAction(recent.type);if(word)speakKo(word);voiceActionKey=key}if(h.id!==prevHand){visualHandId=h.id;visualBoardCount=state.board?.length||0;animateDeal()}else if((state.board?.length||0)>prevBoard){visualBoardCount=state.board.length;animateDeal()}if(h.street==='HAND_COMPLETE'&&(state.results||[]).some(r=>r.playerId===state.me?.playerId&&Number(r.payout)>0))animateWin()}
const premiumRender=renderTable;
renderTable=function(member){return premiumRender(member).replace('<div class="poker-table">','<div class="poker-table"><div class="table-logo">TEXAS HOLD\'EM</div>')};
const premiumMenu=openMenu;
openMenu=function(){premiumMenu();const bg=document.getElementById('bgmToggle')||document.getElementById('soundToggle');if(!bg)return;const row=document.createElement('button');row.className='menu-row';row.id='voiceToggle';row.innerHTML=`<span>한글 액션 음성</span><small>${voiceOn?'켜짐':'꺼짐'}</small>`;bg.insertAdjacentElement('afterend',row);row.onclick=()=>{voiceOn=!voiceOn;localStorage.setItem('holdem_voice',voiceOn?'1':'0');row.querySelector('small').textContent=voiceOn?'켜짐':'꺼짐';if(voiceOn)speakKo('음성 안내 켜짐');glassTap()}};
